### ISSUE TITLE
Add build and runtime requirements to readme

### ISSUE THREAD

**Issue by seek-dev** [ShadowBlip/OpenGamepadUI#1]
Hey dude, 

I spent a little time today getting the main branch running.  Already had both X11 and sway installed, then grabbed godot4-b6 from AUR, so those pull in their own dependencies, but **opengamepad-ui** cannot, nor does it list what it relies on.

From what I can see it looks like it needs wayland, gamescope, X11, xorg-xwayland, xcb, and probably others?  I'm also assuming that it cannot be built with Godot < v4.0? Can we get a list of requirements?

Also, I don't have much experience with Godot, but is there a way to import assets and build this  headlessly?  I do pretty much everything over ssh, but godot refuses to build the project unless I run the editor in a GUI session even with the `--headless` option.  I get a mountain of errors about assets need to be imported in the editor.  After opening and closing the editor a few times it finally decided to import.  Seems like there should be a way to automate that headlessly.

I'd really rather not ever need to run a huge GUI IDE just to build a binary if possible, haha

**Comment by ShadowApex** [comment]
Hey! I'll try and prioritize adding more documentation and setup instructions. It's still really early in development, so I just haven't spent the time adding that just yet. I think you pretty much have the requirements down: gamescope, godot4, xorg-xwayland, and whatever packages provide `xprop` and `xwininfo` (until I can add a native c++ module to set X atoms).

You _should_ be able to build it over SSH, but I haven't tested it. I have the build command in the Makefile, so you should be able to run `make build` to produce the binary. Could you post the output if you still have errors doing it headlessly?

**Comment by seek-dev** [comment]
Thanks.

No rush; just wanted to let you know that the requirements felt missing.  Also seems odd to simultaneously require wayland and xorg libraries and utilities.  Some clarification for dependency use would be cool.

Moved discussion of build issue to #2 

Have a great day!

**Comment by ShadowApex** [comment]
I've updated the README with build and runtime requirements. Gamescope relies on xorg-wayland, so that should be pulled in as a dependency.

Gamescope itself is a Wayland compositor, which manages its own sandboxed xwayland instances. So when you launch an application through gamescope, it renders it in its xwayland. The reason for this is that nearly all Linux games only natively support X11, although I think wine/proton are currently working on a native wayland implementation.
