### ISSUE TITLE
Opening side menus (main/QAM) shows the home menu behind the current menu

### ISSUE THREAD

**Issue by ShadowApex** [ShadowBlip/OpenGamepadUI#151]
When on any menu other than home (e.g. Library, Settings, etc.), and you open up the main menu or QAM, the home menu is shown behind the current menu:

![image](https://github.com/ShadowBlip/OpenGamepadUI/assets/376460/4b26b457-0a09-45d8-a7c0-a593f5311840)

This is due to how `VisibilityManager` is implemented, which has a `visible_during` property that allows menus to be visible when the main menu, qam, and OSK are being shown.

One potential way this could be fixed could be to use a separate `StateMachine` for these overlay menus (main menu, qam, and OSK). We would just need some mechanism to re-focus the current menu when no states remain in the overlay menu state machine.

**Comment by philmmanjaro** [comment]
At least in 0.34.1 I don't see that issue anymore. The Library screen has now a gray background.
