### ISSUE TITLE
Other OS Support?

### ISSUE THREAD

**Issue by Fancy2209** [ShadowBlip/OpenGamepadUI#165]
Hello,

I have just found this project and I was curious if there were any plans to support more OSes than GNU/Linux based ones as my primary gaming machine is still on windows.

**Comment by pastaq** [comment]
We don't currently have plans to support anything other than Linux and it is highly unlikely that we will change that position based on the technical requirements of the project.

**Comment by Fancy2209** [comment]
I see, thanks for letting me know and I wish you the best of luck with this project!
