### ISSUE TITLE
Feature Request , Lutris Launch support 

### ISSUE THREAD

**Issue by EnTaroKerrigan** [ShadowBlip/OpenGamepadUI#169]
I don't use steam library and flatpak etc, I managed my game with lutris. Is it possible to have a lutris plugin to add lutris game to opengameui . 
I really love this project and its idea but it is unusable for me.....

**Comment by pastaq** [comment]
This would be really great. We'll need to do a lot to figure out if Lutris can do everything it needs to headless like provide a library, install and remove games, and report on installed apps.

**Comment by EnTaroKerrigan** [comment]
The library doesn't exist as what I know. 
Here is a possible way to build up a library.
Maybe we can try this ?!

Step 1 there is a sql lite 3 file . We can extract game name  from the table with a couple of SQL commands.(.local/share/lutris/pga.db)
Step 2 look up game yml files with the game name extract from SQL table.
There is a executable and wine prefix path in there (.config/lutris/games/*.yml)
Step 3 Launch game with executable  we get from step 2 

Adding or removing games shouldn't be something necessary. As we can always plug keyboard and mouse to manage library.

Think of this,   when we hold a  beer , plugging in TV and computer , grab a controller and sit on sofa to spend a afternoon. It would be good to launch game directly.  Not like logging to laptop ,start a remote session , launch game , and put laptop away , and finally start playing games. 
This is what I have been doing for years .i really want to have a good solution.   And I had exactly the same idea to create a interface with Godot engine and python.

**Comment by Lx32** [comment]
> The library doesn't exist as what I know. Here is a possible way to build up a library. Maybe we can try this ?!
> 
> Step 1 there is a sql lite 3 file . We can extract game name from the table with a couple of SQL commands.(.local/share/lutris/pga.db) Step 2 look up game yml files with the game name extract from SQL table. There is a executable and wine prefix path in there (.config/lutris/games/*.yml) Step 3 Launch game with executable we get from step 2
> 
> Adding or removing games shouldn't be something necessary. As we can always plug keyboard and mouse to manage library.
> 
> Think of this, when we hold a beer , plugging in TV and computer , grab a controller and sit on sofa to spend a afternoon. It would be good to launch game directly. Not like logging to laptop ,start a remote session , launch game , and put laptop away , and finally start playing games. This is what I have been doing for years .i really want to have a good solution. And I had exactly the same idea to create a interface with Godot engine and python.

In theory it should be sufficient to read the database and then use the command:
`lutris lutris:rungame/slug`
where the slug is the second column of the games table in the database. In this way it will launch the game via Lutris mantaining all the configurations done.

**Comment by pastaq** [comment]
> The library doesn't exist as what I know. Here is a possible way to build up a library. Maybe we can try this ?!
> 
> Step 1 there is a sql lite 3 file . We can extract game name from the table with a couple of SQL commands.(.local/share/lutris/pga.db) Step 2 look up game yml files with the game name extract from SQL table. There is a executable and wine prefix path in there (.config/lutris/games/*.yml) Step 3 Launch game with executable we get from step 2
> 
> Adding or removing games shouldn't be something necessary. As we can always plug keyboard and mouse to manage library.
> 
> Think of this, when we hold a beer , plugging in TV and computer , grab a controller and sit on sofa to spend a afternoon. It would be good to launch game directly. Not like logging to laptop ,start a remote session , launch game , and put laptop away , and finally start playing games. This is what I have been doing for years .i really want to have a good solution. And I had exactly the same idea to create a interface with Godot engine and python.

Ideally we would never oe rarely need to leave the default UI. The primary use case for this is as a console system. Requiring usage of a keyboard is suboptimal.

**Comment by ShadowApex** [comment]
This seems pretty easy to implement a basic library plugin for.

Games configured in lutris can be discovered by running `lutris --list-games -j` to list configured Lutris games in JSON format. Then the launch command for each game could be `lutris lutris:rungame/slug` as mentioned by @Lx32

**Comment by pastaq** [comment]
> This seems pretty easy to implement a basic library plugin for.
> 
> Games configured in lutris can be discovered by running `lutris --list-games -j` to list configured Lutris games in JSON format. Then the launch command for each game could be `lutris lutris:rungame/slug` as mentioned by @Lx32

What about running lutris installations?

**Comment by ShadowApex** [comment]
> What about running lutris installations?

This would involve more work. We'd need to create a Store implementation for Lutris that would use lutris.net for the install manifests.

**Comment by pastaq** [comment]
I suppose launch support with desktop installs is a good starting point for now.

**Comment by ShadowApex** [comment]
I've implemented a basic library provider plugin for Lutris here:
https://github.com/ShadowBlip/OpenGamepadUI-lutris

It can be downloaded from the plugin store menu in OpenGamepadUI.

If you'd like to report any bugs or request additional Lutris features, please open an issue in that plugin repository. Thanks!
