### ISSUE TITLE
Vulkan renderer on Godot Engine 4.1 freezes on some platforms

### ISSUE THREAD

**Issue by ShadowApex** [ShadowBlip/OpenGamepadUI#211]
Testing on the OXP, OpenGamepadUI v0.16+ (using Godot Engine 4.1) hangs on startup using the default Vulkan renderer. I was able to workaround the issue by passing `--rendering-driver opengl3` to the launch command to force using the OpenGL renderer.

![image](https://github.com/ShadowBlip/OpenGamepadUI/assets/376460/259030a6-0a4a-497c-b478-35a296802c8d)

When using the `--verbose` flag, I noticed the following log message which may be relevant:

```
Vulkan: Early suboptimal swapchain, recreating
```

**Comment by ShadowApex** [comment]
After some testing, it seems that this only happens when running under `gamescope -e`.

**Comment by pastaq** [comment]
This shouldn't have been closed as the issue still exists with the Vulkan renderer. Switching to opengl is a workaround not a solution.

**Comment by pastaq** [comment]
Does this still happen in godot 4.2?

**Comment by ShadowApex** [comment]
> Does this still happen in godot 4.2?

Tested the Vulkan renderer on the OXP with Godot 4.2.1 and it seems to be fixed! I will add a follow up PR to switch back to the Vulkan renderer.
