### ISSUE TITLE
[Feature Request] Allow External controller to Open OGUI-QAM and control it.

### ISSUE THREAD

**Issue by spikerguy** [ShadowBlip/OpenGamepadUI#229]
Currently OGUI-QAM can only be opened with onboard controller. 

**Expected Behavior:** 
Guide + B to open QAM no matter which controller is used, if it is from Onboard controller of the device or external controller connected over Bluetooth.

Even when OGUI-QAM is opened from on-board controller, then external controller cannot take over it to access the power-tool menu's.

Thanks for all the work done by the team.

**Comment by pastaq** [comment]
This should be working currently. Can you provide some additional information?
- Hardware used in test, including the base system and controller
- A copy of `~/.ogui-stdout.log` after enabling global debug then attempting to open the menu. You can do this by running `echo LOG_LEVEL=debug > ~/.config/environment.d/99-ogui-logs.conf` and restarting.

**Comment by ShadowApex** [comment]
This issue should now be fixed in v0.20.0. Let us know if you still have issues with external controllers on a handheld.

Thanks!

**Comment by spikerguy** [comment]
> This issue should now be fixed in v0.20.0. Let us know if you still have issues with external controllers on a handheld.
> 
> Thanks!

Just pkged 0.20.2 and it does not add this function. 

tried it on 2 devices. 
1. WinMax2
2. GTR7

On Winmax2 I can open OGUI-QAM using Menu + B but cannot control using external control.
Only new thing is when I open OGUI-QAM then I am able to navigate it using the keyboard arrow keys.

How can I get logs on Manjaro, Cause the method mentioned above it for chimera only.

**Comment by pastaq** [comment]
> How can I get logs on Manjaro, Cause the method mentioned above it for chimera only.

Are you not using the opengamepadui session? This is built in to the session scripts and isn't chimeraos specific.

**Comment by spikerguy** [comment]
I am using it with ogui-session.

I have some logs, I will upload it tonight after work. 

Thanks.

**Comment by spikerguy** [comment]
Here I have tried to bring up qam multiple time. 
[ogui-stdout.log](https://github.com/ShadowBlip/OpenGamepadUI/files/12369255/ogui-stdout.log)

I  will document details too.

**Comment by spikerguy** [comment]
Hey,

Did a short video trying to explain the issues. 
I have faced the following issues with multiple use case.
1. USB-Wireless Keyboard Use Case:
1a.  OGUI-QAM only opens on initial launch where the keyboard is not yet detected as a hid for navigation use or keyboard is detected by OGUI but not steam client. Here I can access OGUI-QAM but cannot nagivate on steam client. I have to click on mousepad or click anywhere to make steam client aware of the hid device. 
1b. Once Navigation works on steam client then I cannot launch OGUI-QAM using Ctrl + F2 on keyboard.
2. External Controller: Guilikit KingKong Pro2
2a. Can never launch OGUI-QAM but can launch steam qam using Menu + A

**Comment by ShadowApex** [comment]
> 1. USB-Wireless Keyboard Use Case:
>        1a.  OGUI-QAM only opens on initial launch where the keyboard is not yet detected as a hid for navigation use or keyboard is detected by OGUI but not steam client. Here I can access OGUI-QAM but cannot nagivate on steam client. I have to click on mousepad or click anywhere to make steam client aware of the hid device.
>        1b. Once Navigation works on steam client then I cannot launch OGUI-QAM using Ctrl + F2 on keyboard.

Keyboard support is a different issue than gamepad support. Could you open a separate issue for this case? This has to do with Gamescope's keyboard focus, which is what determines which app will get keyboard input. When first starting up, OGUI has keyboard focus, but when you use the mouse to click anywhere in the Steam window, it will change keyboard focus to the Steam window.

In order to support pressing CTRL+F2 to open the QAM while in-game or in Steam, we'll need to look into a good solution to do so. One option is to intercept keyboard input like we intercept gamepad input, but this can introduce security concerns as OpenGamepadUI would be able to listen to every keystroke you enter.

> 2\. External Controller: Guilikit KingKong Pro2
>         2a. Can never launch OGUI-QAM but can launch steam qam using Menu + A

Is the log you posted from when you tried opening the QAM with your Guilikit KingKong Pro2 controller? Looking at the end of the log it seems like it is opening the QAM:

```
2026571 [DEBUG] [ManagedGamepad] :0: Translated event <EvdevEvent: EV_KEY BTN_MODE 1> into <EvdevEvent: EV_KEY BTN_MODE 1>
2026571 [DEBUG] [ManagedGamepad] :0: Mode Pressed!
2026571 [DEBUG] [ManagedGamepad] :0: Mode DOWN (Catch)!
2026623 [DEBUG] [ManagedGamepad] :0: Open dat QAM BB
2026624 [DEBUG] [ManagedGamepad] :0: send_input: InputEventAction: action="ogui_qam", pressed=true
2026637 [DEBUG] [OnlyQAMInputManager] :0: Incoming event: InputEventAction: action="ogui_qam", pressed=true
2026638 [DEBUG] [FocusStack] :0: Pushed focus stack: [FocusGroup:<Node#147421400211>]
2026638 [INFO] [FocusGroup] :0: Viewport grabbing focus on node: PowerToolsCard
2026638 [INFO] [Main-OnlyQAM] :0: _on_qam_open state: home
2026638 [DEBUG] [GamepadManager] :0: Setting gamepad intercept mode: 3
2026638 [DEBUG] [ManagedGamepad] :0: Setting intercept mode to: 3
2026638 [INFO] [GlobalStateMachine] :0: Switched from state home to quick_access_menu
2026638 [INFO] [GlobalStateMachine] :0: Stack: home-> quick_access_menu
```
