### ISSUE TITLE
[Feature Request] Make Powertool remember last settings.

### ISSUE THREAD

**Issue by spikerguy** [ShadowBlip/OpenGamepadUI#230]
Power tool will reset all its value to default after every reboot.

It will be a good for user experience to save the setting somewhere and reuse it after every reboot?

**Comment by pastaq** [comment]
This will come around the same time as per-game profiles, at it uses similar logic.

**Comment by spikerguy** [comment]
> This will come around the same time as per-game profiles, at it uses similar logic.

What about when it is `--only-qam` mode ? Here SteamdeckUI is the base instead of OGUi.

**Comment by pastaq** [comment]
> > This will come around the same time as per-game profiles, at it uses similar logic.
> 
> What about when it is `--only-qam` mode ? Here SteamdeckUI is the base instead of OGUi.

OGUI is the base in either case. Steam is running as a subprocess under OGUI in only-qam mode.

**Comment by ShadowApex** [comment]
> > This will come around the same time as per-game profiles, at it uses similar logic.
> 
> What about when it is `--only-qam` mode ? Here SteamdeckUI is the base instead of OGUi.

OGUI has game launch detection, so it will work in both only-qam mode and the full session.

**Comment by ShadowApex** [comment]
This should now be implemented in v0.21.0 from #245
