### ISSUE TITLE
[Feature Request] CEC support.

### ISSUE THREAD

**Issue by BoukeHaarsma23** [ShadowBlip/OpenGamepadUI#244]
See also the repo here https://github.com/Pulse-Eight/libcec

CEC allows to use the TV remote as it where a setup box. Is not only the raspberry PI, but also other external hardware.

**Comment by pastaq** [comment]
I have one of these adapters. What sort of functionality are you looking for on OpenGamepadUI? I would imagine it would be most appropriate at the OS level and be translated to some sort of uinput device.

**Comment by pastaq** [comment]
This would be most appropriate to include in InputPlumber
