### ISSUE TITLE
Create virtual gamepad configuration interface

### ISSUE THREAD

**Issue by ShadowApex** [ShadowBlip/OpenGamepadUI#30]
We're currently using libevdev to intercept gamepad input and direct it to a virtual gamepad. As a result, we should be able to allow users to customize their controller mappings, send virtual keypresses, etc.

**Comment by pastaq** [comment]
This should also support detecting known handheld controllers and allowing remapping of their face buttons. These devices typically register as a keyboard or mouse device, so we'll need to either write extremely specialized udev rules or find a way to employ a polkit. The first option is more desirable as option 2 will require a daemon to interface between OGUI and libinput for polkit to function. The downside is it may be difficult to specialize the UDEV rule, but a combination of physical address and dmi data should suffice. This would make HandyGCCS obsolete.
