### ISSUE TITLE
When exiting a Steam game normally, Steam continues to run, preventing us from detecting the game has closed

### ISSUE THREAD

**Issue by ShadowApex** [ShadowBlip/OpenGamepadUI#31]
Detecting when games close is complex. Normally, when we launch a non-Steam game, we get the process ID of the thing we just launched, and can check if that PID has died. Easy peasy:

```
gamescope (pid 10)
  \---- opengamepadui (pid 11) - { I launched you with pid 12! }
          \---- game (pid 12)
```

Steam, however, doesn't make it easy for us. When you launch a Steam game, it launches a "steam launcher" script, where its whole job is to start up Steam and then die.

```
gamescope (pid 10)
  \---- opengamepadui (pid 11) - { I launched you with pid 12! }
          \---- steam (pid 12) - { Ok, time to die! }
                 \---- steam-for-real (pid 13)
```

This has the fantastic consequence of orphaning the _real_ Steam process.

```
gamescope (pid 10)
  \---- opengamepadui (pid 11)
          \---- (defunct)
                 \---- steam-for-real (pid 13)
```

This is a common technique called [double-fork](https://stackoverflow.com/questions/881388/what-is-the-reason-for-performing-a-double-fork-when-creating-a-daemon), where a process will fork itself, and then die. It's a way to try and daemonize a process. When a process gets orphaned, the init process (pid 1) or a [SUBREAPER](https://linux.die.net/man/2/prctl#PR_SET_CHILD_SUBREAPER) becomes its new parent. In this case, gamescope takes the poor orphan in.

```
gamescope (pid 10)
  |---- opengamepadui (pid 11) - { Did the game just die? }
  \       \---- (defunct)
   \--- steam-for-real (pid 13)
          \---- game (pid 14)
```

We might actually be able to use [subreaper](https://iximiuz.com/en/posts/dealing-with-processes-termination-in-Linux/) ourselves to make Steam re-parent to us, which might make things a bit easier. But right now, to OGUI, it looks like the game just died.  _Luckily_ we have a few tricks to find where Steam went. Whenever we spawn a process, it also has a [PGID](https://linux.die.net/man/2/getpgid) or process group ID! We can use that to determine what decedents might still be hanging around.

```
gamescope (pid 10)
  |---- opengamepadui (pid 11) - { Hey wait, you still have children around! }
  \       \---- (defunct) (pid: 12, pgid: 12)
   \--- steam-for-real (pid 13, pgid: 12) 
          \---- game (pid 14, pgid: 12)
```

Great! Now we can find the decedents of our process we launched. If we want to exit a game, we can just kill all the decedents. That brings us to our next problem: Steam doesn't like to die. If `game` crashes or exits normally, Steam sticks around. There's not a super robust way to detect what the real game is.

```
gamescope (pid 10)
  |---- opengamepadui (pid 11) - { Hmmm, not sure if game, or just steam processes... }
  \       \---- (defunct) 
   \--- steam-for-real (pid 13, pgid: 12) 
          \---- (defunct)
```

There's a few things we could try:

* Create a "blacklist" of Steam processes that we shouldn't consider a game.
  * Games might take a little while to launch, so Steam processes are all there will be until it launches. What if it never launches?
  * What if we just want to launch Steam by itself?
  * This is very Steam-specific and won't work with other launchers.
* Look for `STEAM_GAME` window properties. 
  * This is very Steam-specific and won't help us with other kinds of launchers.

???

**Comment by pastaq** [comment]
One thing we can do to somewhat mitigate this is launch/configure supported DRM versions without steam.

https://steam.fandom.com/wiki/List_of_DRM-free_games

This list appears to be windows-centric so some testing will be required.

There are also 3rd party DRM controlled games:
https://www.pcgamingwiki.com/wiki/The_big_list_of_third-party_DRM_on_Steam

We may be able to manage launching some of those independently.

**Comment by pastaq** [comment]
PR_SET_CHILD_SUBREAPER  seems like it is designed with this problem in mind.
