### ISSUE TITLE
On GPD Win Max 2 using the gamepad makes opengamepadui stuck in keyup press

### ISSUE THREAD

**Issue by fishman** [ShadowBlip/OpenGamepadUI#330]
Whenever I try to use the my GPD win max 2 gamepad it gets stuck immediately and will not stop pressing the key up. It doesn't happen in other games only in opengamepadui.

The driver for this device is xpad.

**Comment by pastaq** [comment]
This was actually already "solved" with a workaround in #328, we just need to publish it to the AUR bin package. I'll leave this open as a reminder to do that. Thanks.
