### ISSUE TITLE
Graphical glitches

### ISSUE THREAD

**Issue by gas-was-taken** [ShadowBlip/OpenGamepadUI#333]
![Screenshot_2024-04-30_15-21-06](https://github.com/ShadowBlip/OpenGamepadUI/assets/166496493/37bdf4e7-399f-418f-8a71-064e32ee11c2)
Hello!
With the latest built, I'm getting weird artifacts whenever I launch opengamepadui. Could that be a driver issue? My computer is really bad (intel HD 620 and 4G of RAM), so the issue is maybe from there.
I'm using Debian 12 with a custom kernel (6.8.4). The issue is also present on the stock kernel.
Thanks in advance, have a great day.
If you need more information, feel free to ask me!

**Comment by pastaq** [comment]
We are using the vulkan backend. Is that device vulkan capable?

**Comment by pastaq** [comment]
Is this still an issue?

**Comment by gas-was-taken** [comment]
Hey! I switched to using a more recent distribution and a better laptop since then, and opengamepadui is working charmingly well. It must have been an issue with my laptop :)
