### ISSUE TITLE
Integrated GPD win max2  controller is no longer detected by opengamepadui

### ISSUE THREAD

**Issue by fishman** [ShadowBlip/OpenGamepadUI#346]
The controller detection randomly stopped working and I don't really know why.

**Comment by ShadowApex** [comment]
Could you provide more information about your installation? E.g. OpenGamepadUI version, OS, etc.

As of  [v0.31.0](https://github.com/ShadowBlip/OpenGamepadUI/releases/tag/v0.31.0), [InputPlumber](https://github.com/ShadowBlip/InputPlumber/) is required for controller support. If you had auto-updates enabled, it may have updated to the latest version.
