### ISSUE TITLE
Prevent extra guide events in full session mode

### ISSUE THREAD

**Issue by philmmanjaro** [ShadowBlip/OpenGamepadUI#374]
With 4538625b1b5102fa122765876c005cac806a81f6 I see the left menu triggered (via guide) when I play a Steam game by pressing RB button on the OrangePi Neo when using the full session mode of Opengamepad UI. When I check with evtest using the xbox elite profile I see only `(BTN_TR), value 0` triggered. When I use the overlay mode in a steam-plus session it acts normal. However there was an extra fix for cutting off extra GUIDE events via de446c249893917d64f6dbb8f488650c396e579e. I assume a similar fix is needed for full session mode too. Also check if 4538625b1b5102fa122765876c005cac806a81f6 is really setting the guide button event correctly for non inputplumber inputs.

**Comment by ShadowApex** [comment]
@pastaq I think we can resolve this by checking to see if InputPlumber is being used. If it is, we can update the Godot input map to remove the appropriate gamepad mappings so input will only be processed by InputPlumber.

**Comment by pastaq** [comment]
Perhaps it would be better for InputPlumber to clear the mappings instead once a manager initializes.
