### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by puzavac** [ShadowBlip/OpenGamepadUI#391]
Maybe a Qt app aimed at mouse and keyboard.

**Comment by ShadowApex** [comment]
It is already possible to run OpenGamepadUI on the desktop using Gamescope's nested mode, but the project's goals are not really meant for desktop usage. It is meant to provide a console-like experience for living room PCs and handhelds.

There are several other great projects that are targeted at desktops:
- [Lutris](https://lutris.net/)
- [Heroic Games Launcher](https://heroicgameslauncher.com/)
- [Pegasus Frontend](https://pegasus-frontend.org/)
- [Cartidges](https://github.com/kra-mo/cartridges)
- [GameHub](https://tkashkin.github.io/projects/gamehub/)

**Comment by puzavac** [comment]
I know it's aimed at console-like experience but I'm sure many would like to see it in a desktop app too. Take for example Steam client app vs. Deck mode.

The alternatives you mention are good for some things but not this. They lack your scope.

From what I gather your project is the closest thing to openly reimplementing Steam's local part. By combining it with various existing open-source online projects, it can come close to reimplementing Steam's entire thing.
