### ISSUE TITLE
[QUESTION] Why godot? Why not GTK 4?

### ISSUE THREAD

**Issue by quluseslignux** [ShadowBlip/OpenGamepadUI#415]
Hi, I really can not understand why Godot was chosen for this type of project instead of GTK 4. I searched on the readthedocs page but couldn't find the answer. I genuinely believe GTK 4 would be a better tool for this project and I'm interested to find the reasoning (technical and not) of choosing Godot.

**Comment by pastaq** [comment]
There are a few reasons we went with Godot, but I'll first state that this question is essentially an infinite loop. Had we gone with GTK4 someone would inevitably ask why we didn't use Qt or Element or <insert name of another UI library>. Each has its own strengths and weaknesses and I'm not really interested in debating the merits of each. There were many reasons we chose to use Godot. This is by no means an exhaustive list, but I figure its worth having on the record for others to find later.

1.) Familiarity. We were already using Godot for years in various gaming projects and enjoy using it.
2.) Language Flexibility. The native GD Script is similar to python in syntax and speed of development, and with GD Extensions we can offload most of the heavy processing functions to more performant languages. We are also able to use more modern languages like Rust for this. While C is capable, it can be very time consuming to master and neither of us write much C in our day to day careers.
3.) Signaling in Godot is really great for responding to global events that might need multiple subsystems to react.
4.) Built-in controller support. While most of the UI is managed by DBus signaling at this point, we initially used input events and still have them as a fallback mechanism. The InputEvent system is also extendable quite easily which makes it perfect for reusing the same physical input event in different scenarios while avoiding huge match trees and endless if cases for what the "A" button should do at any given time.
5.) Extremely composable scene tree and re-usability of Nodes and Resources. 
6.) We like to promote and contribute to FOSS projects we believe in. I think Godot is highly underrated in the gaming industry and we wanted to highlight how flexible it can be.
7.) We wanted to. It is our project and we can chose to use whatever we want. If you'd like to create a GTK4 project that does what this project does then I encourage you to do so.

**Comment by quluseslignux** [comment]
Thank you so much for the reply and explaining the reasoning behind this decision. This are all solid arguments in favour of Godot. OGUI is a project of top importance in the Lignux gaming ecosystem and i wish it great success and you a good day.
