### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by AlexDev404** [ShadowBlip/OpenGamepadUI#416]
Hey 👋🏻 

I really like what you have going here in your project, and wanted to see if I could get it up and running on Windows, but unfortunately it requires some libraries that aren't quite supported in Windows.

So I just wanted to ask--is there any plans (maybe in the future, probably) for support to be rolled out for Windows?

Thanks so much once again for taking the time to develop this!

**Comment by pastaq** [comment]
There are no plans to ever support Windows.

**Comment by ShadowApex** [comment]
@AlexDev404 , as pastaq mentioned, there are no plans to support Windows. OpenGamepadUI relies on several projects like Gamescope, InputPlumber, and PowerStation which are Linux-only projects.

**Comment by AlexDev404** [comment]
@ShadowApex Okay, I understand now. Thanks so much for the clarification on that. Do take care 😊
