### ISSUE TITLE
Frontloader install instructions?

### ISSUE THREAD

**Issue by KP2048** [ShadowBlip/OpenGamepadUI#83]
I have a cool thing I made, Frontloader, and this would be the perfect kind of thing to use with it. https://github.com/EmuDeck/Frontloader

**Comment by Witherking25** [comment]
Essentially, it just launches a binary underneath a nested gamescope session, so if it will work in vanilla gamescope session, it should work fine. There are some example frontend configs in the assets directory, but I might need to have a launcher script that doesn't disable steam integration on gamescope

**Comment by pastaq** [comment]
we use a custom gamescope session which is bundled in the binary as part of the overlayos. see https://github.com/ShadowBlip/OpenGamepadUI-session

**Comment by Witherking25** [comment]
Why do you have a separate session for qam? Is there a binary I can just start to load the ui?

**Comment by Witherking25** [comment]
I already have a custom session script for things that should work fine

**Comment by Witherking25** [comment]
I already have a custom session script for things that should work fine. It seems that the local installation method will work with this, just need to tweak some of my scripts so that the steam one accepts the full command as argument

**Comment by Witherking25** [comment]
Frontloader is designed to not need any rootfs mods or fs overlays, it abuses a thing with the devkit to load instead of steam

**Comment by Witherking25** [comment]
Essentially if you place an executable at `~/devkit-game/devkit-steam`, vanilla gamescope session will load it instead of steam

**Comment by pastaq** [comment]
> Why do you have a separate session for qam? Is there a binary I can just start to load the ui?

There are two modes of operation. The full suite, which acts as the DE and library manager for all games as well as managing system devices such as bluetooth, wifi, audio, display, etc. The second mode is just the opengamepadui qam running with valves gamepadui as the primary interface. This second method is to use OGUI as a plugin manager essentially, for things like power control and any other OGUI plugin that operates from the QAM.  This is more of a "transitional" mode for devices other than steamdeck that need TDP controls, without the use of things like DeckyLoader which break a lot due to valve shenanigans.

**Comment by pastaq** [comment]
> Frontloader is designed to not need any rootfs mods or fs overlays, it abuses a thing with the devkit to load instead of steam

We need the overlayfs for a few functions, but they're all packaged within the binary so it shouldn't affect anything outside the self contained session. You would just need a target for the binary that handed off control of gamescope. @ShadowApex might have more insight here as he built the session.

**Comment by Witherking25** [comment]
Actually you don't need to, Frontloader nests gamescope so that it doesn't mess with steam

**Comment by pastaq** [comment]
Cool. Is there anything else you need or can we close the issue?

**Comment by Witherking25** [comment]
Not really, other than maybe adding the local install one to the installer for use in Frontloader

**Comment by pastaq** [comment]
> Not really, other than maybe adding the local install one to the installer for use in Frontloader

I'm sorry, I'm not understanding what you mean here. Can you restate that with more details?

**Comment by Witherking25** [comment]
The one that installs to ~/.local/bin
